// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_char_codepoint_ from "./routes/api/char/[codepoint].ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $char_codepoint_ from "./routes/char/[codepoint].tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $tag_tag_ from "./routes/tag/[tag].tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/char/[codepoint].ts": $api_char_codepoint_,
    "./routes/api/joke.ts": $api_joke,
    "./routes/char/[codepoint].tsx": $char_codepoint_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/tag/[tag].tsx": $tag_tag_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
